### ISSUE TITLE
About 'MSR-VTT' dataset.

### ISSUE THREAD

**Issue by q-rong** [hobincar/RecNet#20] opened 2019-12-09 13:51 UTC
Hi,

When I was training the model with the `MSR-VTT` dataset, I encountered the following error. I lack the `total.json` file, can you provide it?

`IOError: [Errno 2] No such file or directory: 'data/MSR-VTT/metadata/total.json'`

Thank you very much. 

Best wish.

**Comment by hobincar** [comment] 2019-12-10 04:07
Hi,

I uploaded the file at `'data/MSR-VTT/metadata/total.json'`. Thank you for reporting the missing file :)

**Comment by q-rong** [comment] 2019-12-10 13:46
Hi,

I noticed that the `MSR-VTT` dataset you used was only 7,927 videos. Among them, the `train set` was 5,175, the `val set` was 398, and the `test set` was 2,354.

However, there are 10,000 `MSR-VTT-10K` datasets mentioned in this paper. Among them, there were 6513 `train set`, 497 `val set` and 2990 `test set`.

This seems inconsistent. Is it because of inconsistent data sets that the results of the model are lower?

Why don't you use the `MSR-VTT-10K` dataset?

**Comment by hobincar** [comment] 2019-12-10 15:33
You might have seen [the lines](https://github.com/hobincar/RecNet/blob/master/configs/train_stage1.py#L42-L44) that specify the number of a train, a validation, and a test dataset, respectively. Those numbers were true when I manually download the MSR-VTT dataset with a script, and some videos were missing as they were not available anymore. However, after I found [this link](https://github.com/VisionLearningGroup/caption-guided-saliency/issues/6) that provides the full MSR-VTT dataset I could train the RecNet with all videos.

Those (legacy) numbers do not affect the operation of the model and just there only for giving us information. As it is no longer true, I'll remove it to avoid confusion.

**Comment by q-rong** [comment] 2020-01-07 03:21
Hi,

I noticed that when training the model on the `MSVD` dataset, the learning rate was allowed to change after the 20th epochs.

However, the `MSVD` dataset was set to train 50 epochs, while the `MSR-VTT-10K` dataset only trained 30 epochs.

May I ask, when training the model on the `MSR-VTT-10K` dataset, is the learning rate change also allowed at the beginning of the 20th epochs?

**Comment by hobincar** [comment] 2020-01-18 20:20
Yes, that's what I intended. However, you can find a better learning rate policy since I did not carefully choose it. The 20th is what I found to be good for the MSVD dataset, and I just applied the same to the MSR-VTT dataset.

**Comment by maoao686868** [comment] 2020-12-08 02:02
@q-rong Hi ,when you test run.py with the inception.v4 features from MSVD dataset, did you meet this problem？
Traceback (most recent call last):
  File "run.py", line 96, in <module>
    run('/root/Workspace/rn/checkpoint/RecNet-global_MSVD(1).ckpt')
  File "run.py", line 44, in run
    decoder.load_state_dict(checkpoint['decoder'])
  File "/root/anaconda3/envs/rn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Decoder:
	size mismatch for embedding.weight: copying a param with shape torch.Size([13380, 468]) from checkpoint, the shape in current model is torch.Size([13475, 468]).
	size mismatch for out.weight: copying a param with shape torch.Size([13380, 512]) from checkpoint, the shape in current model is torch.Size([13475, 512]).
	size mismatch for out.bias: copying a param with shape torch.Size([13380]) from checkpoint, the shape in current model is torch.Size([13475]).

**Comment by hobincar** [comment] 2021-02-05 10:13
Seems to be a duplicate of https://github.com/hobincar/RecNet/issues/32.

**Closed as completed by hobincar** 2021-02-05 10:13 UTC
